<?php

namespace Database\Seeders;

use App\Models\Question;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    public function run()
    {
        // read file database/seeders/questions.json and seed from this json
        $json = file_get_contents(database_path('seeders/questions.json'));
        $data = json_decode($json, true);

        foreach ($data as $datum) {
            Question::create([
                'id' => $datum['id'],
                'alphabet_id' => $datum['alphabet_id'],
                'question' => $datum['question'],
                'answer' => $datum['answer'],
                'release_at' => $datum['release_at'],
                'level' => $datum['level'],
            ]);
        }

        $data = [
            "Ağaç: Yeşil yaprakları, dalları ve kökleri olan, dışarıda büyüyen uzun bitki.",
            "Ahtapot: Denizde yaşayan, sekiz tane uzun kolu olan bir deniz hayvanı.",
            "Akasya: Sıcak iklimlerde yetişen, büyük ve gölgelik yaprakları olan bir ağaç türü.",
            "Akrep: Zehirli bir kuyruğu olan ve çöl gibi sıcak yerlerde yaşayan bir böcek türü.",
            "Albatros: Uzun kanatları olan, deniz üzerinde uzun mesafeler uçabilen büyük bir kuş türü.",
            "Ampul: Işık veren, camdan yapılmış elektrikli aydınlatma aracı.",
            "Anakonda: Uzun ve kalın, Güney Amerika'da yaşayan büyük bir yılan türü.",
            "Ananas: Sert kabuklu, yapraklı ve içi tatlı, sarı renkli tropikal bir meyve.",
            "Araba: Tekerlekli, motorlu veya motorsuz her türlü kara taşıtı.",
            "Arı: Bal yapmak için çiçeklerden nektar toplayan, uçan küçük böcek.",
            "Arkeoloji: Geçmişte yaşamış insanların ve uygarlıkların kalıntılarını inceleyen bilim dalı.",
            "Armut: Yuvarlak ve tatlı, ağaçta yetişen bir meyve.",
            "Arşiv: Belge, resim, film gibi bilgi kaynaklarının saklandığı yer.",
            "Asit: Bazı yiyeceklerde bulunan ve ekşi bir tada sahip kimyasal madde.",
            "Astronomi: Gökyüzündeki yıldızlar, gezegenler ve diğer gök cisimlerini inceleyen bilim dalı.",
            "Atmosfer: Dünya'yı çevreleyen ve hava ile dolu olan katman; soluduğumuz hava burada bulunur.",
            "Ayakkabı: Ayakları korumak için giyilen, genellikle deriden yapılan nesne.",
            "Badem: İçi beyaz, kabuğu sert, besleyici bir kuruyemiş türü.",
            "Balık: Suda yaşayan ve yüzgeçleri olan canlı.",
            "Balıkçı: Denizden veya nehirden balık tutan kişi.",
            "Balina: Büyük, denizde yaşayan ve memeli bir hayvan türü.",
            "Balon: Renkli, şişirilebilen, havada uçabilen ince kauçuk.",
            "Bambu: Hızla büyüyen, sert ve uzun gövdeleri olan bir bitki türü.",
            "Bardak: İçecekleri içmek için kullanılan, genellikle camdan yapılan kap.",
            "Biber: Yemeklere lezzet katmak için kullanılan, kırmızı, yeşil veya sarı renkli sebze.",
            "Bisiklet: İki tekerleği olan, pedallarla hareket ettirilen araç.",
            "Boncuk: Takı yapımında kullanılan küçük, delikli ve renkli süs eşyası.",
            "Böcek: Çeşitli türleri olan, genellikle küçük boyutlu omurgasız hayvan.",
            "Böğürtlen: Ormanlarda bulunan, siyah veya kırmızı, sulu ve tatlı bir meyve.",
            "Bulut: Gökyüzünde süzülen, yağmurun kaynağı beyaz veya gri şekiller.",
            "Cam: Şeffaf, kırılgan bir malzeme, pencere yapımında kullanılır.",
            "Cetvel: Düz çizgiler çizmek veya ölçü almak için kullanılan uzun, ince araç.",
            "Ceylan: İnce bacaklı, zarif ve hızlı koşabilen bir vahşi hayvan.",
            "Cips: İnce dilimlenmiş patatesin yağda kızartılmasıyla yapılan atıştırmalık.",
            "Civciv: Yeni doğmuş, sarı tüyleri olan küçük tavuk.",
            "Cüzdan: Para ve kartların saklandığı küçük, katlanabilir çanta.",
            "Çadır: Geçici barınak olarak kullanılan, bez veya naylondan yapılan taşınabilir yapı.",
            "Çakal: Kurtlara benzer, vahşi ve küçük bir etobur memeli.",
            "Çanta: Eşyaları taşımak için kullanılan, genellikle omuza asılan nesne.",
            "Çapa: Toprağı işlemek için kullanılan, uzun saplı ve metal başlıklı bir tarım aracı.",
            "Çaydanlık: Su kaynatmak veya çay demlemek için kullanılan mutfak eşyası.",
            "Çekiç: Çivileri çakmak veya nesneleri vurmak için kullanılan alet.",
            "Çekirge: Uzun bacakları olan ve zıplayarak hareket eden, yeşil renkli bir böcek.",
            "Çiçek: Renkli yaprakları olan ve genellikle güzel kokan bitki parçası.",
            "Çilek: Kırmızı, tatlı ve sulu, bahçelerde yetişen bir meyve.",
            "Çorap: Ayakları sıcak tutmak için giyilen kumaş veya yün nesne.",
            "Davul: Vurularak çalınan, yuvarlak bir müzik aleti.",
            "Deniz: Büyük ve geniş su kütlesi, okyanusa benzer.",
            "Denizanası: Denizde yaşayan, şeffaf ve jelatinimsi bir deniz canlısı.",
            "Dikiş: Kumaş parçalarını birleştirmek için iplikle yapılan işlem.",
            "Dinozor: Çok eskiden dünyada yaşamış, büyük ve farklı türleri olan hayvanlar.",
            "Diş: Ağzımızda bulunan, yiyecekleri ısırıp çiğnememize yarayan sert yapılar.",
            "Dodo: Nesli tükenmiş, uçamayan büyük bir kuş türü.",
            "Dolap: Eşyaları saklamak için kullanılan, kapaklı büyük mobilya.",
            "Dolunay: Ay'ın tamamen aydınlık ve yuvarlak göründüğü gece evresi.",
            "Domates: Salatalarda kullanılan, kırmızı ve yuvarlak bir sebze.",
            "Düdük: Üfleyerek ses çıkartılan, genellikle plastikten yapılan küçük müzik aleti.",
            "Dürbün: Uzakları yakın gösteren, iki tüpten oluşan optik alet.",
            "Ebru: Özel bir teknikle su üzerinde yapılan ve kağıda aktarılan geleneksel Türk sanatı.",
            "Ejderha: Ateş püskürten, kanatlı ve efsanevi bir yaratık.",
            "Ekose: Kareli desenli kumaş veya giysi.",
            "Eldiven: Elleri korumak için giyilen, parmaklı kumaş veya deri nesne.",
            "Elma: Yuvarlak, sulu ve genellikle kırmızı veya yeşil renkte meyve.",
            "Enerji: Işıkları yakmak, araçları hareket ettirmek gibi işler için gerekli güç.",
            "Eşarp: Başa veya boyna takılan, genellikle kare şeklinde kumaş.",
            "Eşek: Dört ayaklı, insanlara yük taşıma işinde yardımcı olan hayvan.",
            "Fare: Küçük, kuyruklu kemirgen hayvan.",
            "Fener: Karanlıkta yol gösteren, içinde ampul olan taşınabilir ışık kaynağı.",
            "Fırça: Saç düzeltmek, boyama yapmak veya temizlik için kullanılan uzun saplı araç.",
            "Fırfır: Kıyafet süslemelerinde kullanılan, kıvrımlı bez parçası.",
            "Fırın: Yemek pişirmek için kullanılan ısıtıcı ev aleti.",
            "Fıstık: Yeşil kabuklu, içi yenilebilir, besleyici bir kuruyemiş.",
            "Fincan: Çay veya kahve içmek için kullanılan, genellikle küçük ve saplı kap.",
            "Flamingo: Uzun bacakları ve boyunları olan, pembe renkli bir kuş türü.",
            "Flüt: Ufleyerek çalınan, ince uzun bir müzik aleti.",
            "Fosil: Milyonlarca yıl önce yaşamış canlıların kalıntıları.",
            "Fotoğraf: Kameralarla çekilen ve kağıda basılan resim.",
            "Gelincik: Kırmızı çiçekleri olan, tarlalarda yetişen bir bitki türü.",
            "Gemi: Su üzerinde seyahat etmek için kullanılan büyük araç.",
            "Geyik: Ormanlarda yaşayan, boynuzlu büyük bir memeli hayvan.",
            "Gitar: Telleri çalınarak müzik yapılan bir çalgı aleti.",
            "Gonca: Henüz açmamış, genç çiçek.",
            "Gökyüzü: Uçakların ve kuşların uçtuğu, bulutların süzüldüğü mavi veya siyah alan.",
            "Gözlük: Görme bozukluklarını düzeltmek için kullanılan, iki camlı bir çerçeve.",
            "Gül: Güzel kokulu, çeşitli renklerde olabilen popüler bir çiçek.",
            "Güneş: Güneş sisteminin merkezindeki, kendi ışığını ve ısısını üreten yıldız.",
            "Güvercin: Şehirlerde yaygın olarak bulunan, barışın simgesi olarak bilinen bir kuş türü.",
            "Halı: Yere serilen, renkli desenleri olan kumaş veya yün örtü.",
            "Hamsi: Karadeniz'e özgü küçük ve lezzetli bir balık türü.",
            "Harita: Dünya'nın veya herhangi bir yerin kağıt üzerine çizilmiş şekli.",
            "Havlu: Elleri veya vücudu kurulamak için kullanılan emici kumaş.",
            "Havuç: Toprağın altında yetişen, turuncu renkli bir sebze.",
            "Hazine: Altın, mücevher ve değerli eşyaların saklandığı gizli yer.",
            "Hediye: Doğum günleri veya özel günlerde sevdiklerimize verdiğimiz sürprizler.",
            "Helikopter: Üstünde dönen pervaneleriyle havalanan ve uçan bir araç.",
            "Hindi: Büyük ve tüylü, genellikle çiftliklerde yetiştirilen bir kuş türü.",
            "Hoparlör: Sesleri yükseltmek için kullanılan elektronik cihaz.",
            "Horoz: Tavukgillerden, sabahları öten erkek kuş.",
            "Hortum: Güçlü rüzgarlarla oluşan, havada dönen hava sütunu.",
            "Hurma: Yumuşak, tatlı ve uzunca bir meyve, genellikle Ortadoğu'da yetişir.",
            "Iğdır: Türkiye'nin doğusunda yer alan bir şehir.",
            "Ihlamur: Yapraklarından çay yapılan, hoş kokulu bir ağaç.",
            "Irmak: Uzun ve genellikle doğal su yolu.",
            "Ispanak: Yeşil yaprakları olan, demir açısından zengin bir sebze.",
            "Işık: Güneşten veya lambadan gelen parlak enerji.",
            "İbis: Uzun bacaklı, uzun gagalı bir su kuşu türü.",
            "İğne: Kumaş dikmek için kullanılan ince, uzun metal parça.",
            "İnci: İstiridyelerin içinde oluşan, parlak ve değerli bir taş.",
            "İncir: Yumuşak, tatlı ve sulu, içinde çok sayıda küçük çekirdeği olan meyve.",
            "İp: Bağlamak veya bir şeyi asmak için kullanılan uzun, ince, bükülmüş lifler.",
            "İstiridye: Denizde yaşayan, sert kabuklu ve içinde inci bulunabilen bir deniz canlısı.",
            "Jaguar: Güçlü, hızlı ve etobur, Amerika kıtasına özgü büyük bir kedi türü.",
            "Jandarma: Askeri ve polisiye görevleri olan güvenlik teşkilatı.",
            "Japon Balığı: Renkli ve süs amaçlı beslenen küçük bir akvaryum balığı.",
            "Jel: Saç şekillendirme veya cilt bakımı için kullanılan yapışkan ve yumuşak madde.",
            "Jelatin: Yemeklerde veya tatlılarda katılaştırıcı olarak kullanılan madde.",
            "Jelibon: Renkli, şekerli ve yumuşak, çocukların sevdiği bir şeker türü.",
            "Jenga: Ahşap blokların dikkatlice çekilip üst üste konulduğu bir oyun.",
            "Jet: Çok hızlı uçan, genellikle askeri veya özel amaçlı kullanılan uçak.",
            "Jeton: Oyun makinelerinde veya bazı toplu taşıma araçlarında kullanılan madeni para.",
            "Jilet: Tıraş olmak için kullanılan ince ve keskin metal bıçak.",
            "Kabuk: Ağaçların dışını kaplayan sert tabaka veya meyvelerin dış kısmı.",
            "Kaktüs: Suları içinde tutabilen, dikenli ve çöl bitkisi.",
            "Kalem: Yazmak veya çizim yapmak için kullanılan araç.",
            "Kanguru: Uzun kuyruğu ve büyük ayakları olan, zıplayarak hareket eden bir hayvan.",
            "Kaplumbağa: Sert kabuğu olan ve yavaş hareket eden bir hayvan.",
            "Karpuz: Büyük, yeşil kabuklu ve içi kırmızı, sulu bir yaz meyvesi.",
            "Kartal: Büyük, güçlü ve yüksekten uçabilen bir yırtıcı kuş.",
            "Kavun: Büyük, sulu ve tatlı, genellikle yaz aylarında yenilen bir meyve.",
            "Kedi: Evde beslenen, tüylü ve mırıldayan bir hayvan.",
            "Keman: Yayla çalınan, klasik müzik aleti.",
            "Kivi: Kahverengi kabuklu, yeşil içli, tatlı bir meyve.",
            "Kuşburnu: Çalı tipi bitkilerde yetişen, C vitamini açısından zengin kırmızı meyve.",
            "Lale: Renkli ve gösterişli çiçekleri olan, bahçelerde yetişen bir bitki.",
            "Lamba: Işık vermek için kullanılan elektrikli alet.",
            "Lavanta: Mor çiçekleri olan ve hoş kokusuyla bilinen bir bitki.",
            "Limon: Ekşi, sarı renkli ve yuvarlak bir meyve.",
            "Limonata: Limon suyu, su ve şeker karışımından yapılan serinletici içecek.",
            "Lor: Bir tür peynir, genellikle taze ve yumuşak kıvamlı.",
            "Mağara: Dağlarda veya yer altında bulunan, doğal olarak oluşmuş büyük boşluk.",
            "Mangal: Açık havada et pişirmek için kullanılan, kömürle çalışan ocak.",
            "Mantar: Ormanlarda bulunan, yenilebilen veya zehirli olabilen bir tür fungus.",
            "Masa: Üzerine eşya konulan düz ve genellikle dört ayaklı mobilya.",
            "Maymun: Ağaçlarda yaşayan, insanlara benzer hareketleri olan zeki bir hayvan.",
            "Merdiven: Farklı seviyeler arasında geçiş yapmak için kullanılan basamaklı yapı.",
            "Mıknatıs: Demir gibi bazı metalleri kendine çeken nesne.",
            "Mum: Işık vermek için yakılan, genellikle silindir şeklinde balmumu veya parafinden yapılmış nesne.",
            "Muz: Sarı, uzun ve eğri, tropikal bir meyve.",
            "Nane: Ferahlatıcı kokusu olan, çaylarda ve yemeklerde kullanılan bir bitki.",
            "Nar: İçi taneli ve kırmızı, vitamin açısından zengin bir meyve.",
            "Nehir: Uzun ve genellikle doğal su yolu.",
            "Neptün: Güneş sistemimizdeki mavi renkli, soğuk ve gazdan oluşan bir gezegen.",
            "Nergis: İlkbaharda açan, hoş kokulu, beyaz veya sarı renkli çiçekleri olan bir bitki.",
            "Neşe: Mutluluk ve sevinç hali.",
            "Nilüfer: Suda yetişen, büyük ve renkli çiçekleri olan bir bitki türü.",
            "Oda: Bir ev veya bina içinde belirli bir amaç için ayrılmış bölüm.",
            "Ok: Yayla atılan, uç kısmı sivri, uzunca bir silah.",
            "Okul: Eğitim ve öğrenim görülen yer.",
            "Orkide: Çeşitli renk ve şekillerde çiçek açan, zarif bir bitki türü.",
            "Orman: Çok sayıda ağacın ve bitkilerin bulunduğu, hayvanların yaşadığı alan.",
            "Ödül: İyi bir iş veya başarı için verilen armağan veya takdir.",
            "Öğretmen: Okullarda ders veren ve öğrencilere bilgi öğreten kişi.",
            "Ördek: Göletlerde yaşayan, suya uyum sağlamış bir kuş türü.",
            "Örgü: İlmek ilmek bağlanarak yapılan, genellikle yün ile yapılan el işi.",
            "Örümcek: Sekiz bacaklı ve ağ örebilen küçük bir hayvan.",
            "Öykü: Kısa, yazılı hikaye.",
            "Palyaço: Renkli kıyafetler giyen ve insanları güldüren eğlence sanatçısı.",
            "Papağan: Renkli tüyleri ve taklit yeteneği ile bilinen bir kuş türü.",
            "Papatya: Beyaz yapraklı, sarı merkezli, yaygın bulunan bir çiçek türü.",
            "Patates: Yemeklerde yaygın olarak kullanılan, yer altında yetişen bir kök sebze.",
            "Pelikan: Büyük, uzun bir gagası olan ve balıkla beslenen bir kuş türü.",
            "Penguen: Kutuplarda yaşayan, siyah ve beyaz tüylü, yüzebilen bir kuş türü.",
            "Peynir: Sütten yapılan, çeşitli tatlarda ve kıvamlarda bir yiyecek.",
            "Pil: Elektrikli cihazları çalıştırmak için enerji sağlayan küçük silindir şeklinde nesne.",
            "Radyasyon: Atom çekirdeklerinden yayılan enerji dalgaları veya parçacıkları.",
            "Radyo: Müzik veya haber yayını yapan elektronik cihaz.",
            "Rakun: Maske benzeri yüz deseni olan, küçük ve zeki bir memeli hayvan.",
            "Renk: Mavi, yeşil, sarı gibi gözümüzle gördüğümüz çeşitli görüntüler.",
            "Robot: İnsanlar tarafından programlanabilen, bazen insan işlerini yapabilen makine.",
            "Roket: Uzaya gitmek için kullanılan uzun ve ince araç.",
            "Rokoko: 18. yüzyılda popüler olmuş, süslü ve ayrıntılı sanat tarzı.",
            "Ruj: Dudaklara renk vermek için kullanılan makyaj malzemesi.",
            "Saat: Zamanı ölçmek için kullanılan alet.",
            "Sahra: Geniş, kuru ve çoğunlukla kumsal olan çöl alanı.",
            "Saksafon: Üflemeli bir müzik aleti, caz müziğinde sıkça kullanılır.",
            "Salyangoz: Yavaş hareket eden ve sırtında kabuğu olan bir hayvan.",
            "Samur: Kürkü için değerli bulunan, küçük bir memeli hayvan.",
            "Sandal: Küçük, su üzerinde hareket edebilen basit bir tekne.",
            "Sincap: Ağaçlarda yaşayan, sevimli ve hızlı hareket edebilen küçük bir memeli.",
            "Sinek: Küçük, uçan ve bazen rahatsız edici bulunan bir böcek türü.",
            "Sümbül: İlkbaharda çiçek açan, güzel kokulu bir bitki.",
            "Sünger: Temizlikte kullanılan, suyu emebilen yumuşak madde.",
            "Şakayık: Bahçelerde yetişen, büyük ve gösterişli çiçekleri olan bir bitki.",
            "Şapka: Başa giyilen, güneşten koruyan veya süs amaçlı kullanılan aksesuar.",
            "Şeftali: Yumuşak, tüylü kabuğu olan ve içi tatlı bir meyve.",
            "Şeker: Tatlı yiyecek ve içeceklerde kullanılan, beyaz kristalize madde.",
            "Şempanze: İnsana benzer özelliklere sahip, zeki bir maymun türü.",
            "Şemsiye: Yağmurda ıslanmamak için kullanılan, katlanabilir, taşınabilir araç.",
            "Tavşan: Uzun kulakları ve hızlı koşabilen küçük bir hayvan.",
            "Tavuk: Yumurta veren ve eti için yetiştirilen çiftlik kuşu.",
            "Tilki: Kırmızımsı kürkü olan, zeki bir yaban hayvanı.",
            "Timsah: Güçlü çenesi ve pullu derisi olan, su kenarında yaşayan büyük bir sürüngen.",
            "Tost: İki dilim arasına peynir veya diğer malzemeler konularak yapılan sıcak sandviç.",
            "Tren: Raylar üzerinde ilerleyen, yolcu veya yük taşıyan uzun araç.",
            "Turp: Toprağın altında yetişen, kırmızı veya beyaz renkli bir sebze.",
            "Uçak: Gökyüzünde uçarak insanları ve eşyaları taşıyan büyük araç.",
            "Ud: Telli bir müzik aleti, geleneksel Türk ve Arap müziğinde kullanılır.",
            "Uğur Böceği: Kırmızı ve siyah benekli, küçük ve sevimli bir böcek.",
            "Umut: İyi bir şeyin olacağına dair içten gelen inanç.",
            "Uydu: Dünya'nın veya başka bir gezegenin çevresinde dönen yapay veya doğal cisim.",
            "Uzay: Dünya'nın atmosferinin dışında kalan, yıldızlar ve gezegenlerin bulunduğu sonsuz boşluk.",
            "Üçgen: Üç köşesi olan geometrik bir şekil.",
            "Ütopya: İdeal ve kusursuz toplum düzeni anlamına gelen bir kavram.",
            "Ütü: Kıyafetleri düzleştirmek için kullanılan sıcak elektrikli alet.",
            "Üveç: Yemek pişirmek için kullanılan, genellikle topraktan yapılan kap.",
            "Üzüm: Salkımlar halinde yetişen ve şarap yapımında kullanılan meyve.",
            "Vagon: Trenin yolcu veya yük taşıyan bölümleri.",
            "Vanilya: Tatlılarda kullanılan, hoş kokulu bir baharat.",
            "Vapur: Su üzerinde yolcu ve yük taşıyan büyük bir tekne.",
            "Vazo: Çiçek koymak için kullanılan süs eşyası.",
            "Vişne: Küçük, kırmızı ve ekşi tatlı bir meyve.",
            "Vitrin: Mağazalarda ürün sergilemek için kullanılan camlı dolap veya alan.",
            "Vizon: Kürkü için yetiştirilen, küçük ve hızlı bir hayvan.",
            "Volkan: Yer kabuğunda, lav ve kül püskürten doğal oluşum.",
            "Yabanmersini: Ormanlarda yetişen, küçük ve mor renkli bir meyve.",
            "Yakamoz: Ay ışığının denizde yansıması sonucu oluşan parıltı.",
            "Yaprak: Ağaç ve bitkilerin yeşil parçaları.",
            "Yelken: Rüzgar gücüyle hareket eden teknelerde kullanılan, kumaştan yapılmış büyük parça.",
            "Yengeç: Denizde yaşayan, iki büyük pençesi olan bir kabuklu hayvan.",
            "Yılan: Bacaksız, uzun ve sürüngen bir hayvan.",
            "Yıldız: Gökyüzünde parlayan ışık kaynağı.",
            "Yosun: Sulak alanlarda veya nemli yerlerde büyüyen, yeşil renkli bitki.",
            "Yunus: Akıllı, oyunbaz ve suda yaşayan bir memeli hayvan.",
            "Zambak: Büyük ve kokulu çiçekleri olan, süs bitkisi olarak kullanılan bir bitki.",
            "Zarf: Mektup veya kartpostal göndermek için kullanılan kağıt kılıf.",
            "Zebra: Siyah ve beyaz çizgili, atgiller familyasından bir hayvan.",
            "Zeytin: Akdeniz iklimine özgü, yağ yapımında kullanılan yeşil veya siyah meyve.",
            "Zirkon: Takı yapımında kullanılan, parlak ve renkli bir mineral.",
            "Zümrüt: Yeşil renkli, değerli ve parlak bir taş.",
            "Zürafa: Uzun boyunlu ve büyük bir memeli hayvan.",
        ];

        $alphabet = \App\Models\Alphabet::all();

        foreach ($data as $datum) {
            // structure is: "word: definition"
            $word = explode(': ', $datum)[0];
            $definition = explode(': ', $datum)[1];
            $char = mb_substr($word, 0, 1, 'UTF-8');
            $alphabet_id = $alphabet->where('name', $char)->first()->id;

            if (Question::where('answer', $word)->where('level', 1)->exists()) {
                // info("Question $word already exists, skipping...");
                // info($word);
                continue;
            }

            Question::create([
                'alphabet_id' => $alphabet_id,
                'question' => $definition,
                'answer' => $word,
                'release_at' => now(),
                'level' => 1,
            ]);
        }
    }
}
